shortcuts +/- changed to Ctrl-g/Ctrl-h

diff --git a/odexp b/odexp
--- a/odexp
+++ b/odexp
@@ -11,27 +11,33 @@ ODEXPDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
 set -eu # makes your program exit on error or unbound variable
 
+# require gawk
+hash gawk 2>/dev/null || { echo >&2 "I require gawk but it's not installed.  Aborting."; exit 1; }
+
 mkdir -p .odexp
 
 echo "# odexp file name: $1" >.odexp/sub.odexp
-echo "# In this file, all constant (variable starting with _n)" >>.odexp/sub.odexp
+echo "# In this file, all constant (variable starting with _)" >>.odexp/sub.odexp
 echo "# are replaced with their value" >>.odexp/sub.odexp
 echo "" >>.odexp/sub.odexp
 
 # replace all constants (variable starting with '_') by their value
 # remove all ending ;
 # replace all ; by \n 
-awk '$1 !~ /#/ {gsub(";( )*$","",$0)};
+gawk '$1 !~ /#/ {gsub(";( )*$","",$0)};
     $1 !~ /#/ {gsub(";","\n"$1,$0)};
     $1 ~ /^( )*_/ {n++; name[n]=$1; val[n]=$2; };
     $1 !~ /^( )*_/ { 
         if(n>0) {
             for(i=1;i<=n;i++) {
-                gsub(name[i],val[i],$0);
+                gsub(name[i]"\\>",val[i],$0);
             }
         }
     };
     {print $0}' $1 >>.odexp/sub.odexp
+
+
+
 file=.odexp/sub.odexp
 
 # if two input files, then second one should contain parameters
@@ -43,7 +49,7 @@ fi
 
 
 declare_iterators () {
-    awk -F ' ' -v i=1 '/(\[.+\])+/ && $1 !~ /#/ { match($2,/(\[.+\])+/);
+    gawk -F ' ' -v i=1 '/(\[.+\])+/ && $1 !~ /#/ { match($2,/(\[.+\])+/);
         a=substr($2, RSTART, RLENGTH);
         split(a,b,/[\[\]=:]/);
         for(k=2;k<=length(b);k+=4) 
@@ -85,7 +91,7 @@ declare_iterators () {
 }
 
 set_defines () {
-    awk -F ' ' '$1 ~ /^[sS][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' '$1 ~ /^[sS][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
         var=$2;
         $1="";
         $2="";
@@ -95,7 +101,7 @@ set_defines () {
 }
 
 system_defines () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[sS][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[sS][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs = $2;
       split($0,ex," ");
       printf "S%-3d %-16s", nv, lhs;
@@ -111,7 +117,7 @@ system_defines () {
 declare_parametric_expressions () {
     # find parametric expressions and declare them in .odexp/model.c
     # find parametric expression vectors and declare them in .odexp/model.c
-    awk -F ' ' '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       printf "    double %s;\n", $2 };
       $1 ~ /^[eE]/ && $2 ~ /(\[.+\])+/ {match($2,/(\[.+:.+\])+/);
       a=substr($2, RSTART, RLENGTH);
@@ -126,7 +132,7 @@ declare_parametric_expressions () {
 system_parametric_expression () {
     # find parametric expressions and declare them in .odexp/system.par
     # find parametric expression vectors and declare them in .odexp/system.par
-    awk -F ' ' -v nv=0 '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs = $2;
       split($0,ex," ");
       printf "E%-3d %-16s", nv, lhs;
@@ -153,7 +159,7 @@ system_parametric_expression () {
 }
 
 system_auxiliary_functions () {
-   awk -F ' ' -v nv=0 '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+   gawk -F ' ' -v nv=0 '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs = $2; 
       split($0,ex," ");
       printf "A%-3d %-16s", nv, lhs;
@@ -180,7 +186,7 @@ system_auxiliary_functions () {
 }
 
 system_variables () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[dD]{1}[a-zA-Z0-9_]+(\[.+\])*\/[dD]{1}[tT]{1}/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[dD]{1}[a-zA-Z0-9_]+(\[.+\])*\/[dD]{1}[tT]{1}/ {
       lhs = $1;
       split($0,ex," ");
       printf "%-18s = ", lhs;
@@ -193,7 +199,7 @@ system_variables () {
 }
 
 system_init_conditions () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[xXiI][0-9-]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[xXiI][0-9-]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs = $2;
       split($0,ex," ");
       printf "X%-3d %-16s", nv, lhs;
@@ -226,21 +232,21 @@ system_init_conditions () {
 }
 
 system_tspan () {
-    awk -F ' ' '$1 ~ /^[tT][a-zA-Z0-9_]*$/ {
+    gawk -F ' ' '$1 ~ /^[tT][a-zA-Z0-9_]*$/ {
       $1=""; 
       printf "T %s\n", $0
       }' $parfile >>.odexp/system.par
 }
 
 system_options () {
-    awk -F ' ' '$1 ~ /^[oO]/ {
+    gawk -F ' ' '$1 ~ /^[oO]/ {
     $1="";
     printf "O %s\n", $0
     }' $parfile >>.odexp/system.par
 }
 
 system_uniform_random_array () {
-    awk -F ' ' '$1 ~ /^[uU][0-9]*$/  {
+    gawk -F ' ' '$1 ~ /^[uU][0-9]*$/  {
         print $0
        }' $file >>.odexp/system.par
 }
@@ -249,7 +255,7 @@ system_uniform_random_array () {
 declare_variables () {
     # find variables and declare them to model.c
     # find vector variables and declare them to model.c
-    awk -F ' ' '$1 ~ /^[xXiI][0-9]*$/ && $2 !~ /\[.+:.+\]/ {printf "    double %s;\n", $2 };
+    gawk -F ' ' '$1 ~ /^[xXiI][0-9]*$/ && $2 !~ /\[.+:.+\]/ {printf "    double %s;\n", $2 };
       $1 ~ /^[xXiI][0-9]*$/ && $2 ~ /(\[.+:.+\])+/ {match($2,/(\[.+:.+\])+/);
       a=substr($2, RSTART, RLENGTH);
       split(a,b,/[\[\]=:]/);
@@ -263,7 +269,7 @@ declare_variables () {
 declare_auxiliary_functions () {
     # find auxiliary variables and declare them to model.c
     # find vector auxiliary functiond and declare them to model.c
-    awk -F ' ' '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {printf "    double %s;\n", $2};
+    gawk -F ' ' '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {printf "    double %s;\n", $2};
       $1 ~ /^[aA][0-9]*$/ && $2 ~ /(\[.+:.+\])+/ {match($2,/(\[.+:.+\])+/);
       a=substr($2, RSTART, RLENGTH);
       split(a,b,/[\[\]=:]/);
@@ -275,7 +281,7 @@ declare_auxiliary_functions () {
 }
 
 declare_uniform_random_array () {
-    awk -F ' ' '$1 ~ /^[uU][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' '$1 ~ /^[uU][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       printf "    double %s;\n", $2 };
       $1 ~ /^[uU]/ && $2 ~ /(\[.+\])+/ {match($2,/(\[.+:.+\])+/);
       a=substr($2, RSTART, RLENGTH);
@@ -291,7 +297,7 @@ declare_uniform_random_array () {
 assign_parametric_expressions () {
     # assign parametric expressions and declare them in .odexp/model.c
     # assign vector parametric expressions and declare them in .odexp/model.c
-    awk -F ' ' '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' '$1 ~ /^[eE][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs=$2;
       $1="";
       $2="";
@@ -325,7 +331,7 @@ assign_parametric_expressions () {
 
 assign_auxiliary_functions () {
     # assign auxiliary function to model.c
-    awk -F ' ' '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       lhs=$2;
       $1="";
       $2="";
@@ -354,7 +360,7 @@ assign_auxiliary_functions () {
 }
 
 assign_variables () {
-  awk -F ' ' -v nv=0 '$1 ~ /^[dD][a-zA-Z0-9_]+(\[[^:]\])*\/[dD]{1}[tT]{1}/ {
+  gawk -F ' ' -v nv=0 '$1 ~ /^[dD][a-zA-Z0-9_]+(\[[^:]\])*\/[dD]{1}[tT]{1}/ {
       match($1,/^[dD][a-zA-Z0-9_\[\]]+/);
       lhs=substr($1, RSTART+1,RLENGTH-1);
       printf "    %s = y_[%d];\n", lhs, nv; nv++};
@@ -387,7 +393,7 @@ assign_variables () {
 }
 
 assign_equations () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[dD][a-zA-Z0-9_]+(\[[^:]\])*\/[dD]{1}[tT]{1}/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[dD][a-zA-Z0-9_]+(\[[^:]\])*\/[dD]{1}[tT]{1}/ {
       split($0,ex,/=/); printf "    f_[%d] = %s;\n", nv, ex[2]; nv++};
       
       $1 ~ /^[dD][a-zA-Z0-9_]+(\[.+=.+:.+\])+\/[dD][tT]/ {
@@ -411,7 +417,7 @@ assign_equations () {
 }
 
 assign_aux_pointer () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[aA][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       ex=$2;
       printf "    aux_[%d] = %s;\n", nv, ex; nv++
       };
@@ -430,7 +436,7 @@ assign_aux_pointer () {
 }
 
 assign_uniform_random_array () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[uU][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[uU][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       ex=$2;
       printf "    %s = rnd_[%d];\n", ex, nv; nv++
       };
@@ -450,7 +456,7 @@ assign_uniform_random_array () {
 
 
 assign_initial_conditions () {
-    awk -F ' ' -v nv=0 '$1 ~ /^[xXiI][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
+    gawk -F ' ' -v nv=0 '$1 ~ /^[xXiI][0-9]*$/ && $2 !~ /\[.+:.+\]/ {
       $1="";
       $2="";
       ex=$0;
@@ -585,15 +591,15 @@ echo "" >>.odexp/model.c
 
 #echo "# constants " >>.odexp/system.par
 # find variable parameters and declare them in system.par 
-#awk -F ' ' '$1 ~ /^[cC][0-9]*$/ {printf "C%d %s %s\n", i, $2, $3; i++}' $file >>.odexp/system.par
+#gawk -F ' ' '$1 ~ /^[cC][0-9]*$/ {printf "C%d %s %s\n", i, $2, $3; i++}' $file >>.odexp/system.par
 
 echo "" >>.odexp/model.c
 echo "    /* parameters */" >>.odexp/model.c
 # find variable parameters and declare them in model.c 
-awk -F ' ' -v i=0 '$1 ~ /^[pP][0-9]*$/ {printf "    double %s = pars_[%d];\n", $2, i++}' $parfile >>.odexp/model.c
+gawk -F ' ' -v i=0 '$1 ~ /^[pP][0-9]*$/ {printf "    double %s = pars_[%d];\n", $2, i++}' $parfile >>.odexp/model.c
 echo "# parameters " >>.odexp/system.par
 # find variable parameters and declare them in system.par 
-awk -F ' ' '$1 ~ /^[pP][0-9]*$/ {printf "P%-3d %-16s%s\n", i, $2, $3; i++}' $parfile >>.odexp/system.par
+gawk -F ' ' '$1 ~ /^[pP][0-9]*$/ {printf "P%-3d %-16s%s\n", i, $2, $3; i++}' $parfile >>.odexp/system.par
 echo "" >>.odexp/model.c
 # ====================================================================================
 
@@ -724,7 +730,7 @@ echo "" >>.odexp/model.c
 echo "" >>.odexp/model.c
 echo "    /* parameters */" >>.odexp/model.c
 # find variable parameters and declare them in model.c 
-awk -F ' ' -v i=0 '$1 ~ /^[pP][0-9]*$/ {printf "    double %s __attribute__((unused)) = pars_[%d];\n", $2, i++}' $parfile >>.odexp/model.c
+gawk -F ' ' -v i=0 '$1 ~ /^[pP][0-9]*$/ {printf "    double %s __attribute__((unused)) = pars_[%d];\n", $2, i++}' $parfile >>.odexp/model.c
 # ====================================================================================
 
 # ====================================================================================
